# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="tcc"
version="1.0.3"
displayName="TaczCurios"
authors="xlxyvergil"
description="A Minecraft 1.20.1 jewelry mod that adds various accessories with special effects. Dependencies: Curios API and TaczAttributeAdd."

[[dependencies.tcc]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.tcc]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.tcc]]
modId="curios"
mandatory=true
versionRange="[5.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tcc]]
modId="taa"
mandatory=true
versionRange="[1.0.5,)"
ordering="AFTER"
side="BOTH"